title: "Justin Chin Cheong"
email: your.email@example.com
description: >-
  Engineering Portfolio | Mechatronic Systems | Simulations | Robotics | Electronics
baseurl: ""
url: "https://jcchincheong-bb.github.io"
theme: jekyll-theme-cayman

author:
  name: "Justin Chin Cheong"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true