# Main Page Setup

title: Engineering Portfolio 



# Hero Section
name: Justin Chin Cheong
headline: Mechatronics Systems Engineering Student
description: >- # dont remove this line. this will ignore all new lines until the next section
  A diligent engineering student who takes pride in my organisational 
  skills and commitment to my work. My thirst for knowledge has continuously driven me to push beyond 
  my limits in everything I do.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/profile.png


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: https://docs.google.com/document/d/1u12JQ0y7hav6BmOYvICYnxsVlIn-KJHxNh3HGH5gafQ/edit?usp=drive_link # or /assets/resume/resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: justin-chin-cheong-6444421b4    # https://www.linkedin.com/in/{your url slug} 
  github: jcchincheong-bb    # https://github.com/{your url slug} 
  # stackoverflow: test      # https://stackoverflow.com/users/{your url slug}
  # medium:            # https://medium.com/@{your url slug} 
  # x-twitter:   # https://x.com/{your url slug} 
  # threads:            # https://threads.net/@{your url slug} 
  # instragram:       # https://instagram.com/{your url slug} 
  # youtube:           # https://youtube.com/@{your url slug} 
  # discord:            # https://discord.com/users/{your url slug} 
  # bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Programming
    tools:
    - Python
    - MATLAB
    - C
    - HTML
    - CSS
    - JavaScript
  - category: 3D Modelling / CAD
    tools:
    - SolidWorks
    - Fusion 360 
    - AutoCAD
    - 3D Printing
  - category: Simulation
    tools:
    - Simulink (MATLAB)
    - PyBullet (Python)
  - category: PCB Design
    tools:
    - Eagle 
    - KiCad
  - category: Electronic Prototyping
    tools:
    - Microcontrollers (Arduino, Atmega, Raspberry Pi)
    - Breadboarding
    - Electrical Measurements (Multimeter, Oscilloscope)
    - Soldering
  - category: Research and Analysis
    tools:
    - LaTeX
    - Literature Review
    - Data Collection
    - Presentation Skills
  - category: Data Analysis
    tools:
    - Pandas (Python)
    - NumPy (Python)
    - Matplotlib (Python)
    - Excel
    - Financial Estimating
  - category: Soft Skills
    tools:
    - Teamwork
    - Communication
    - Problem Solving
    - Time Management
    - Adaptability
    - Microsoft Office Suite (Word, Excel, PowerPoint)


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key: mdkdldzq



# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
